CI: Bump MSRV for CI from 1.70 to 1.85
    error: failed to download replaced source registry `crates-io`

    Caused by:
      failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.17.1/Cargo.toml`

    Caused by:
      failed to parse the `edition` key

    Caused by:
      this version of Cargo is older than the `2024` edition, and only supports `2015`, `2018`, and `2021` editions.